
// This file has been generated by the GUI designer. Do not modify.
namespace GTKValveViewer
{
	public partial class TextureDisplayWidget
	{
		private global::Gtk.Notebook notebook1;

		private global::Gtk.Image image1;

		private global::Gtk.Label page1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView textview_redi;

		private global::Gtk.Label label2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview_data;

		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GTKValveViewer.TextureDisplayWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "GTKValveViewer.TextureDisplayWidget";
			// Container child GTKValveViewer.TextureDisplayWidget.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.image1 = new global::Gtk.Image();
			this.image1.Name = "image1";
			this.notebook1.Add(this.image1);
			// Notebook tab
			this.page1 = new global::Gtk.Label();
			this.page1.Name = "page1";
			this.page1.LabelProp = global::Mono.Unix.Catalog.GetString("Texture");
			this.notebook1.SetTabLabel(this.image1, this.page1);
			this.page1.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textview_redi = new global::Gtk.TextView();
			this.textview_redi.CanFocus = true;
			this.textview_redi.Name = "textview_redi";
			this.GtkScrolledWindow1.Add(this.textview_redi);
			this.notebook1.Add(this.GtkScrolledWindow1);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.GtkScrolledWindow1]));
			w3.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("REDI");
			this.notebook1.SetTabLabel(this.GtkScrolledWindow1, this.label2);
			this.label2.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview_data = new global::Gtk.TextView();
			this.textview_data.CanFocus = true;
			this.textview_data.Name = "textview_data";
			this.GtkScrolledWindow.Add(this.textview_data);
			this.notebook1.Add(this.GtkScrolledWindow);
			global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.GtkScrolledWindow]));
			w5.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("DATA");
			this.notebook1.SetTabLabel(this.GtkScrolledWindow, this.label3);
			this.label3.ShowAll();
			this.Add(this.notebook1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
