
// This file has been generated by the GUI designer. Do not modify.
namespace GTKValveViewer
{
	public partial class NotebookTabLabel
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GTKValveViewer.NotebookTabLabel
			global::Stetic.BinContainer.Attach(this);
			this.Name = "GTKValveViewer.NotebookTabLabel";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
